---
  - name: Provision webservers
    hosts: tag-group-web
    tasks:

      - name: Install pip3
        apt:
          update_cache: yes
          name: python3-pip
        become: yes

      - name: Install python docker sdk using pip3
        shell: |
          pip3 install docker
        become: yes

      - name: Install docker
        apt:
          name: docker.io
        become: yes

      - name: Start docker service
        shell: |
          systemctl start docker
          systemctl enable docker
        become: yes

      - name: Run Image
        shell: |
          docker stop nginx-container
          docker rm nginx-container
          docker run -dit --name nginx-container -p 8000:8000 -p 443:443 kaokakelvin/nginx-image:latest
        become: yes